package com.google.android.gms.internal.drive;

import com.google.android.gms.common.data.BitmapTeleporter;
import com.google.android.gms.drive.DriveId;
import com.google.android.gms.drive.metadata.MetadataField;
import java.util.Collections;

public final class zzhs {
   public static final MetadataField<DriveId> zzjl;
   public static final MetadataField<String> zzjm;
   public static final zzhv zzjn;
   public static final MetadataField<String> zzjo;
   public static final MetadataField<String> zzjp;
   public static final MetadataField<String> zzjq;
   public static final MetadataField<Long> zzjr;
   public static final MetadataField<String> zzjs;
   public static final MetadataField<Boolean> zzjt;
   public static final MetadataField<String> zzju;
   public static final MetadataField<Boolean> zzjv;
   public static final MetadataField<Boolean> zzjw;
   public static final MetadataField<Boolean> zzjx;
   public static final MetadataField<Boolean> zzjy;
   public static final MetadataField<Boolean> zzjz;
   public static final zzhw zzka;
   public static final MetadataField<Boolean> zzkb;
   public static final MetadataField<Boolean> zzkc;
   public static final MetadataField<Boolean> zzkd;
   public static final MetadataField<Boolean> zzke;
   public static final MetadataField<Boolean> zzkf;
   public static final MetadataField<Boolean> zzkg;
   public static final MetadataField<Boolean> zzkh;
   public static final zzhx zzki;
   public static final MetadataField<String> zzkj;
   public static final com.google.android.gms.drive.metadata.zzb<String> zzkk;
   public static final com.google.android.gms.drive.metadata.internal.zzu zzkl;
   public static final com.google.android.gms.drive.metadata.internal.zzu zzkm;
   public static final com.google.android.gms.drive.metadata.internal.zzo zzkn;
   public static final zzhy zzko;
   public static final zzia zzkp;
   public static final MetadataField<BitmapTeleporter> zzkq;
   public static final zzib zzkr;
   public static final zzic zzks;
   public static final MetadataField<String> zzkt;
   public static final MetadataField<String> zzku;
   public static final MetadataField<String> zzkv;
   public static final com.google.android.gms.drive.metadata.internal.zzb zzkw;
   public static final MetadataField<String> zzkx;
   public static final MetadataField<String> zzky;
   public static final zzhz zzkz;
   public static final MetadataField<String> zzla;
   public static final MetadataField<Boolean> zzlb;

   static {
      zzjl = zzim.zzlj;
      zzjm = new com.google.android.gms.drive.metadata.internal.zzt("alternateLink", 4300000);
      zzjn = new zzhv(5000000);
      zzjo = new com.google.android.gms.drive.metadata.internal.zzt("description", 4300000);
      zzjp = new com.google.android.gms.drive.metadata.internal.zzt("embedLink", 4300000);
      zzjq = new com.google.android.gms.drive.metadata.internal.zzt("fileExtension", 4300000);
      zzjr = new com.google.android.gms.drive.metadata.internal.zzi("fileSize", 4300000);
      zzjs = new com.google.android.gms.drive.metadata.internal.zzt("folderColorRgb", 7500000);
      zzjt = new com.google.android.gms.drive.metadata.internal.zzb("hasThumbnail", 4300000);
      zzju = new com.google.android.gms.drive.metadata.internal.zzt("indexableText", 4300000);
      zzjv = new com.google.android.gms.drive.metadata.internal.zzb("isAppData", 4300000);
      zzjw = new com.google.android.gms.drive.metadata.internal.zzb("isCopyable", 4300000);
      zzjx = new com.google.android.gms.drive.metadata.internal.zzb("isEditable", 4100000);
      zzjy = new zzht("isExplicitlyTrashed", Collections.singleton("trashed"), Collections.emptySet(), 7000000);
      zzjz = new com.google.android.gms.drive.metadata.internal.zzb("isLocalContentUpToDate", 7800000);
      zzka = new zzhw("isPinned", 4100000);
      zzkb = new com.google.android.gms.drive.metadata.internal.zzb("isOpenable", 7200000);
      zzkc = new com.google.android.gms.drive.metadata.internal.zzb("isRestricted", 4300000);
      zzkd = new com.google.android.gms.drive.metadata.internal.zzb("isShared", 4300000);
      zzke = new com.google.android.gms.drive.metadata.internal.zzb("isGooglePhotosFolder", 7000000);
      zzkf = new com.google.android.gms.drive.metadata.internal.zzb("isGooglePhotosRootFolder", 7000000);
      zzkg = new com.google.android.gms.drive.metadata.internal.zzb("isTrashable", 4400000);
      zzkh = new com.google.android.gms.drive.metadata.internal.zzb("isViewed", 4300000);
      zzki = new zzhx(4100000);
      zzkj = new com.google.android.gms.drive.metadata.internal.zzt("originalFilename", 4300000);
      zzkk = new com.google.android.gms.drive.metadata.internal.zzs("ownerNames", 4300000);
      zzkl = new com.google.android.gms.drive.metadata.internal.zzu("lastModifyingUser", 6000000);
      zzkm = new com.google.android.gms.drive.metadata.internal.zzu("sharingUser", 6000000);
      zzkn = new com.google.android.gms.drive.metadata.internal.zzo(4100000);
      zzko = new zzhy("quotaBytesUsed", 4300000);
      zzkp = new zzia("starred", 4100000);
      zzkq = new zzhu("thumbnail", Collections.emptySet(), Collections.emptySet(), 4400000);
      zzkr = new zzib("title", 4100000);
      zzks = new zzic("trashed", 4100000);
      zzkt = new com.google.android.gms.drive.metadata.internal.zzt("webContentLink", 4300000);
      zzku = new com.google.android.gms.drive.metadata.internal.zzt("webViewLink", 4300000);
      zzkv = new com.google.android.gms.drive.metadata.internal.zzt("uniqueIdentifier", 5000000);
      zzkw = new com.google.android.gms.drive.metadata.internal.zzb("writersCanShare", 6000000);
      zzkx = new com.google.android.gms.drive.metadata.internal.zzt("role", 6000000);
      zzky = new com.google.android.gms.drive.metadata.internal.zzt("md5Checksum", 7000000);
      zzkz = new zzhz(7000000);
      zzla = new com.google.android.gms.drive.metadata.internal.zzt("recencyReason", 8000000);
      zzlb = new com.google.android.gms.drive.metadata.internal.zzb("subscribed", 8000000);
   }
}
